import {
  HEADER_FIELDS,
  FINANCIAL_BUDGET_ROWS,
  FINANCIAL_BUDGET_COLUMNS,
  PRODUCTION_DETAIL_FIELDS,
  STOCK_PARTICULAR_ITEMS,
  STOCK_PARTICULAR_COLUMNS,
  RECEIPT_ITEMS,
  SILK_SALES_ROWS,
  PERIOD_KEYS,
  RAW_SILK_PURCHASED_ROWS,
  MACHINE_STOCK_ROWS,
  READY_SILK_ROWS,
  NSC_EXPENDITURE_ROWS,
  COST_OF_PRODUCTION_FIELDS,
  ESTIMATED_RECEIPT_ROWS,
  READY_SILK_SOLD_ROWS,
  TWISTED_WASTE_SOLD_ROWS,
  PENDING_READY_ROWS,
  PENDING_WASTE_ROWS,
  PRESENT_RATE_FIELDS,
  CAPACITY_FIELDS,
  MIS34_REPORT_TITLE,
  MIS34_FORM_CODE,
} from './mis34Constants.js';

export const MIS34_SHARED_HEADER_SECTION = {
  id: 'sharedHeader',
  type: 'fieldGrid',
  title: 'Unit & Period Details',
  path: 'header',
  fields: HEADER_FIELDS,
  sticky: true,
};

export const MIS34_TAB_SECTIONS = [
  {
    id: 'tab1',
    label: 'Achievement & Production',
    sections: [
      {
        id: 'achievementPhysical',
        type: 'fieldGrid',
        title: 'Achievement to Target — Physical',
        path: 'tab1.achievementPhysical',
        columns: 2,
        fields: [
          { key: 'rawProducedTarget', label: 'Raw Produced Target (kg)', type: 'number' },
          { key: 'rawProducedAchieved', label: 'Raw Produced Achieved (kg)', type: 'number' },
          { key: 'twistedSilkTarget', label: 'Twisted Silk Production Target (kg)', type: 'number' },
          { key: 'twistedSilkAchieved', label: 'Twisted Silk Production Achieved (kg)', type: 'number' },
        ],
      },
      {
        id: 'achievementFinancial',
        type: 'matrix',
        title: 'Achievement to Target — Financial Control Budget',
        path: 'tab1.achievementFinancial',
        rows: FINANCIAL_BUDGET_ROWS,
        columns: FINANCIAL_BUDGET_COLUMNS,
      },
      {
        id: 'productionDetails',
        type: 'fieldGrid',
        title: 'Production Details',
        path: 'tab1.productionDetails',
        fields: PRODUCTION_DETAIL_FIELDS,
        columns: 2,
      },
      {
        id: 'stockParticulars',
        type: 'stockParticulars',
        title: 'Stock Particulars',
        path: 'tab1.stockParticulars',
        items: STOCK_PARTICULAR_ITEMS,
        columns: STOCK_PARTICULAR_COLUMNS,
      },
      {
        id: 'receipts',
        type: 'receiptsWithTotal',
        title: 'Receipts (D.M)',
        path: 'tab1.receipts',
        items: RECEIPT_ITEMS,
      },
      {
        id: 'silkSalesRealisation',
        type: 'silkSales',
        title: 'Silk Sales & Realisation (Tansilk, Kancheepuram)',
        path: 'tab1.silkSalesRealisation',
        rows: SILK_SALES_ROWS,
      },
    ],
  },
  {
    id: 'tab2',
    label: 'Stock Registers & NSC Expenditure',
    sections: [
      {
        id: 'rawSilkPurchased',
        type: 'periodRowMatrix',
        title: 'Raw Silk Purchased (Kgs)',
        path: 'tab2.rawSilkPurchased',
        rows: RAW_SILK_PURCHASED_ROWS,
        periods: PERIOD_KEYS,
        extraColumn: { label: 'Source Unit', key: 'sourceUnit', rowKey: 'purchasedReceived' },
      },
      {
        id: 'machineStock',
        type: 'periodRowMatrix',
        title: 'Machine Stock',
        path: 'tab2.machineStock',
        rows: MACHINE_STOCK_ROWS,
        periods: PERIOD_KEYS,
      },
      {
        id: 'readySilkTwisting',
        type: 'warpWeftPeriod',
        title: 'Ready Silk Twisting (Kgs)',
        path: 'tab2.readySilkTwisting',
        rows: READY_SILK_ROWS,
        periods: PERIOD_KEYS,
      },
      {
        id: 'nscExpenditure',
        type: 'nscExpenditurePeriod',
        title: 'NSC Expenditure (Rs)',
        path: 'tab2.nscExpenditure',
        rows: NSC_EXPENDITURE_ROWS,
      },
    ],
  },
  {
    id: 'tab3',
    label: 'Cost, Sales & Profit/Loss',
    sections: [
      {
        id: 'costOfProduction',
        type: 'fieldGrid',
        title: 'Cost of Production (Rs)',
        path: 'tab3.costOfProduction',
        fields: COST_OF_PRODUCTION_FIELDS,
        columns: 1,
      },
      {
        id: 'estimatedReceiptDetails',
        type: 'fieldGrid',
        title: 'Estimated Receipt Details',
        path: 'tab3.estimatedReceiptDetails',
        fields: ESTIMATED_RECEIPT_ROWS,
        columns: 1,
      },
      {
        id: 'actualReceiptDetails',
        type: 'twistingActualReceipts',
        title: 'Actual Receipt Details (Rs)',
        path: 'tab3.actualReceiptDetails',
        readySilkRows: READY_SILK_SOLD_ROWS,
        wasteRows: TWISTED_WASTE_SOLD_ROWS,
        pendingReadyRows: PENDING_READY_ROWS,
        pendingWasteRows: PENDING_WASTE_ROWS,
        rateFields: PRESENT_RATE_FIELDS,
      },
      {
        id: 'capacityOfUnit',
        type: 'fieldGrid',
        title: 'Capacity of the Unit',
        path: 'tab3.capacityOfUnit',
        fields: CAPACITY_FIELDS,
        columns: 2,
      },
      {
        id: 'profitLoss',
        type: 'profitLossSingle',
        title: 'Profit / Loss',
        path: 'tab3.profitLoss',
        formula: 'Total Actual Receipts − Net NSC Expenditure',
      },
    ],
  },
];

export { MIS34_REPORT_TITLE, MIS34_FORM_CODE };
